version: '3.5'

services:

  jenkins:
    image: jenkinsci/blueocean
    user: "root"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Expose the docker daemon in the container
      - ./:/home/node
    ports:
      - "8085:8080"
    networks:
      - devops

networks:
  devops:
    name: devops
    driver: bridge